obj-$(CONFIG_MTK_SOC_THERMAL)	+= auxadc_thermal.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= lvts_thermal.o

# --- merged from MiCode MTK_kernel_device_modules bsp-dali-v-oss ---
obj-$(CONFIG_MTK_SOC_THERMAL)	+= soc_temp.o
obj-$(CONFIG_MTK_SOC_THERMAL_LVTS)	+= soc_temp_lvts.o
obj-$(CONFIG_MTK_PMIC_THERMAL) += pmic_temp.o
obj-$(CONFIG_MTK_MD_THERMAL)	+= md_cooling_all.o
obj-$(CONFIG_MTK_CHARGER_THERMAL) += charger_cooling.o
obj-$(CONFIG_MTK_BACKLIGHT_THERMAL) += backlight_cooling.o
obj-$(CONFIG_MTK_THERMAL_TRACE) += thermal_trace.o
obj-$(CONFIG_MTK_THERMAL_IPI)	+= thermal_ipi.o
obj-$(CONFIG_MTK_THERMAL_INTERFACE)	+= thermal_interface.o
obj-$(CONFIG_MTK_BOARD_THERMAL)	+= board_temp.o
obj-$(CONFIG_MTK_VTSKIN_THERMAL)	+= vtskin_temp.o
obj-$(CONFIG_MTK_WIFI_THERMAL) += wifi_cooling.o
obj-$(CONFIG_MTK_FAN_THERMAL) += fan_cooling.o
obj-$(CONFIG_MTK_CPU_ISOLATE_THERMAL) += cpu_isolate_cooling.o
