# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2018 MediaTek Inc.
#

ifeq ($(srctree),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

IMGSYS_ISP8_MODULE := mtk_imgsys_isp8

#platform dependent
ccflags-y += -I$(KO_CODE_PATH)/../../../mtk-hcp/isp8
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cmdq/mailbox/
ccflags-y += -I$(KO_CODE_PATH)/../../common/
ccflags-y += -I$(KO_CODE_PATH)/../cmdq/isp8
ccflags-y += -I$(KO_CODE_PATH)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/smi/
ccflags-y += -I$(srctree)/drivers/iommu
ccflags-y += -I$(srctree)/drivers/misc/mediatek/iommu
ccflags-y += -I$(srctree)/drivers/misc/mediatek/slbc
ccflags-y += -I$(srctree)/include/soc/mediatek
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/

ifeq ($(CONFIG_MTK_MBRAINK_BRIDGE), m)
ccflags-y += -DCFG_SUPPORT_MBRAIN=1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mbraink

$(info "isp8 ccflags-y = $(ccflags-y)")

check_path := $(shell if [ ! -d $(srctree)/drivers/misc/mediatek/mbraink/bridge ]; then echo "Error: Path $(srctree)/drivers/misc/mediatek/mbraink/bridge not found" >&2; exit 1; fi)
endif

ccflags-y += -ferror-limit=0

$(info "imgsys, isp8 device_module_path = $(srctree)")
$(info "imgsys, isp8 srctree_path = $(srctree)")
$(info "imgsys, isp8 src_path = $(src)")
$(info "imgsys, isp8 ko_code_path = $(KO_CODE_PATH)")

#register TF CB
ifneq ($(wildcard $(srctree)/include/dt-bindings/memory/mt6991-larb-port.h),)
subdir-ccflags-y += -DIMGSYS_TF_DUMP_8_L
endif

ifneq ($(wildcard $(srctree)/include/dt-bindings/memory/mt6899-larb-port.h),)
subdir-ccflags-y += -DIMGSYS_TF_DUMP_8_P
endif

$(info "imgsys, subdir-ccflags-y = $(subdir-ccflags-y)")

subdir-ccflags-y += -DMTK_IOVA_SINK2KERNEL
subdir-ccflags-y += -DMTK_IOVA_NOTCHECK

$(info imgsys DEVICE_MODULES_PATH=$(srctree))
NOTDIR_DEVICE_MODULES_PATH = $(notdir $(srctree))
$(info imgsys NOTDIR_DEVICE_MODULES_PATH=$(NOTDIR_DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
$(info imgsys KERNEL_VERSION=$(KERNEL_VERSION))

#$(info mtk_aov sort=$(sort 6.6 $(KERNEL_VERSION)))
#$(info mtk_aov word=$(word 1,$(sort 6.6 $(KERNEL_VERSION))))

ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DNEW_DMA_BUF_API
endif

$(IMGSYS_ISP8_MODULE)-objs := \
mtk_imgsys-v4l2.o \
mtk_imgsys-dev.o \
mtk_imgsys-sys.o \
mtk_imgsys-isp8.o \
mtk_imgsys-debug.o \
imgsys_modules/mtk_imgsys-dip.o \
imgsys_modules/mtk_imgsys-traw.o \
imgsys_modules/mtk_imgsys-pqdip.o \
imgsys_modules/mtk_imgsys-wpe.o \
imgsys_modules/mtk_imgsys-omc.o \
imgsys_modules/mtk_imgsys-me.o \
imgsys_modules/mtk_imgsys-adl.o

obj-${CONFIG_VIDEO_MTK_ISP_IMGSYS_8} += $(IMGSYS_ISP8_MODULE).o

