# SPDX-License-Identifier: GPL-2.0-only
# Support GKI mixed build
ifeq ($(srctree),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

IMGSYS_HCP_MODULE := mtk_hcp

subdir-ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/2.4
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/iommu/
ccflags-y += -I$(KO_CODE_PATH)/../../imgsys/imgsys/isp7sp/
ccflags-y += -I$(KO_CODE_PATH)/../../imgsys/common/
ccflags-y += -I$(KO_CODE_PATH)/../../imgsys
ccflags-y += -I$(KO_CODE_PATH)
ccflags-y += -I$(srctree)/include/media

$(info "hcp, device_module_path = $(srctree)")
$(info "hcp, srctree_path = $(srctree)")
$(info "hcp, src_path = $(src)")
$(info "hcp, ko_code_path = $(KO_CODE_PATH)")

ifeq ($(CONFIG_MTK_ION),y)
    ccflags-y += -I$(srctree)/drivers/staging/android/mtk_ion/
    ccflags-y  += -I$(srctree)/drivers/staging/android/mtk_ion/mtk/
else
    ccflags-$(CONFIG_ION) += -I$(srctree)/drivers/staging/android/aosp_ion/
endif

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/ \
             -I$(srctree)/drivers/misc/mediatek/include/mt-plat/ \
             -I$(srctree)/drivers/misc/mediatek/include/ \
             -I$(srctree)/drivers/misc/mediatek/slbc/ \
             -I$(srctree)/drivers/dma-buf/heaps/ \
             -I$(srctree)/drivers/iommu

$(info hcp-isp-legacy DEVICE_MODULES_PATH=$(srctree))
NOTDIR_DEVICE_MODULES_PATH = $(notdir $(srctree))
$(info hcp-isp-legacy NOTDIR_DEVICE_MODULES_PATH=$(NOTDIR_DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
$(info hcp-isp-legacy KERNEL_VERSION=$(KERNEL_VERSION))

ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DHCP_NEW_DMA_BUF_API
endif

$(IMGSYS_HCP_MODULE)-objs := \
mtk-hcp.o \
mtk-hcp_isp71.o \
mtk-hcp_isp7s.o \
mtk-hcp_kernelfence.o \
mtk-hcp_isp7sp.o 
#mem/hcp_videobuf2-memops.o \
#mem/hcp_videobuf2-vmalloc.o \
#mem/hcp_videobuf2-dma-contig.o

obj-${CONFIG_VIDEO_MTK_ISP_HCP} += $(IMGSYS_HCP_MODULE).o
