# SPDX-License-Identifier: GPL-2.0-only
# Support GKI mixed build
ifeq ($(srctree),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

AIE_MODULE := mtk_aie


$(info mtk_aie DEVICE_MODULES_PATH=$(srctree))
NOTDIR_DEVICE_MODULES_PATH = $(notdir $(srctree))
$(info mtk_aie NOTDIR_DEVICE_MODULES_PATH=$(NOTDIR_DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
$(info mtk_aie KERNEL_VERSION=$(KERNEL_VERSION))

ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DAIE_DMA_BUF_UNLOCK_API
endif

ccflags-y += -I$(srctree)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cmdq/mailbox/
ccflags-y += -I$(srctree)/drivers/dma-buf/heaps/
ccflags-y += -I$(srctree)/drivers/media/platform/mtk-videobuf/
ccflags-y += -I$(KO_CODE_PATH)/../imgsys/
ccflags-y += -I$(KO_CODE_PATH)/../include/
ccflags-y += -I$(srctree)/drivers/iommu
ccflags-y += -I$(srctree)/drivers/misc/mediatek/iommu
ccflags-y += -I$(srctree)/include/

ifneq ($(wildcard $(srctree)/include/dt-bindings/memory/mt6897-larb-port.h),)
ccflags-y += -DAIE_TF_DUMP_7SP
endif

ifneq ($(wildcard $(srctree)/include/dt-bindings/memory/mt6989-larb-port.h),)
ccflags-y += -DAIE_TF_DUMP_7SP_1
endif

ifneq ($(wildcard $(srctree)/include/dt-bindings/memory/mt6878-larb-port.h),)
ccflags-y += -DAIE_TF_DUMP_7SP_2
endif

$(AIE_MODULE)-objs := \
mem/aie_videobuf2-dma-contig.o\
mem/aie_videobuf2-memops.o\
mem/aie_videobuf2-vmalloc.o\
mtk_aie_53.o\
mtk_aie-trace.o\
mtk_aie_drv_isp7s.o \
mtk_aie_drv_isp7sp.o

obj-$(CONFIG_MTK_CAMERA_FD_ISP7S_ISP7SP) += $(AIE_MODULE).o
obj-$(CONFIG_MTK_CAMERA_FD_ISP7S_ISP7SP) += mtk_aie_debug_7sp.o
obj-$(CONFIG_MTK_CAMERA_FD_ISP7S_ISP7SP) += mtk_aie_debug_7sp_1.o
obj-$(CONFIG_MTK_CAMERA_FD_ISP7S_ISP7SP) += mtk_aie_debug_7sp_2.o